SPPEEEED dial
clayplumridge/initiative-tracker pull request #22
Opened 2021-04-23 02:26 UTC by alex-power

2021-04-23 02:28 UTC, alex-power commented
![image](https://user-images.githubusercontent.com/25554707/115809395-06e75300-a3ba-11eb-825b-bf82d8b23110.png)

2021-04-23 03:16 UTC, clayplumridge commented
Looks like you've got some linter errors. If you install all of the recommended vscode extensions you should be autofixing them on file save. If you don't want to for some reason, run `npm run lint:fix`

2021-04-23 03:27 UTC, clayplumridge requested changes

2021-04-23 03:27 UTC, clayplumridge commented on src/render/theme.ts
> +            disableRipple: false
You can just remove the entire `props` block. This merges with the base dark theme from MUI. Another cool application of the spread operator: `{ ...themeDefaults, ...themeOverrides }`

2021-04-23 03:27 UTC, clayplumridge commented on src/render/views/CreateEncounterView.tsx
> +        },
Looks like most of these styles aren't being used anymore; can probably remove them

2021-04-23 03:27 UTC, clayplumridge commented on src/render/views/CreateEncounterView.tsx
> +    const speedDialActions = [
You could also define this outside of the component definition as top-level static state so we don't re-initialize a bunch of objects on every render of this component. I do this with most maps and arrays like this one. The performance cost is low but can add up on complex pages.

2021-04-23 03:27 UTC, clayplumridge commented on src/render/views/CreateEncounterView.tsx
> +    const handleSpeedDialClose = () => {
These are short enough that you can just inline them in the `SpeedDial` itself as `onOpen={() => setSpeedDialOpen(true)}` etc.

2021-04-23 03:27 UTC, clayplumridge commented on src/render/views/CreateEncounterView.tsx
> +                            ariaLabel="Add Character"
Let's leave all `aria` props out for now. If we want to do an accessibility pass later we definitely can (and likely should) but I'm not sure what the right usage pattern is here so I'd rather leave it alone.

2021-04-23 03:27 UTC, clayplumridge commented on src/render/views/CreateEncounterView.tsx
> +                            onClick={() => console.log("hello")}
Left in by mistake?

2021-04-23 19:01 UTC, clayplumridge commented on src/render/views/CreateEncounterView.tsx
> +    const speedDialActions = [
The other option here is to use `const speedDialActions = React.useMemo(() => [ ... ]);` which will memoize the call so it doesn't recalculate it every render. Not super partial here tbh.

2021-04-23 19:03 UTC, clayplumridge commented on src/render/views/CreateEncounterView.tsx
> +    const speedDialActions = [
I actually think I'd prefer `React.useMemo` after thinking on it a bit here. It encapsulates the info we care about inside the component which is clearer and delays the logic until first render.

2021-04-29 00:15 UTC, clayplumridge approved these changes

2021-04-29 00:16 UTC, merged