Starting on the Create Encounter flow
clayplumridge/initiative-tracker pull request #6
Opened 2021-04-11 01:20 UTC by clayplumridge

2021-04-11 18:43 UTC, grundygolem2 requested changes
No idea why, but I get a scrollbar at the bottom of the +encounters view. plz no.

Also, for this level of PR, can we get a "cancel create" and a delete button on encounters?

2021-04-11 18:45 UTC, clayplumridge commented
> No idea why, but I get a scrollbar at the bottom of the +encounters view. plz no.

Can you grab a SS?

> Also, for this level of PR, can we get a "cancel create" and a delete button on encounters?

Yeah should be doable

2021-04-12 15:36 UTC, grundygolem2 approved these changes

2021-04-12 15:36 UTC, grundygolem2 commented on src/render/components/TextField.tsx
> +    extends Omit<MuiTextFieldProps, "onChange" | "value"> {
What is Omit?

2021-04-12 15:36 UTC, grundygolem2 commented on src/render/views/EncounterManagementView.tsx
> +            padding: theme.spacing(1),
y is this the fix, gross, but w/e

2021-04-12 15:40 UTC, clayplumridge commented on src/render/views/EncounterManagementView.tsx
> +            padding: theme.spacing(1),
Not sure tbh.

2021-04-12 15:40 UTC, clayplumridge commented on src/render/components/TextField.tsx
> +    extends Omit<MuiTextFieldProps, "onChange" | "value"> {
It's the first type parameter minus the fields from the second type parameter, for the purposes of clear overriding in this case

2021-04-12 15:41 UTC, merged